#!/bin/sh
killall dunst
notify-send -i /usr/share/icons/Adwaita/24x24/status//usr/share/icons/Adwaita/24x24/status/audio-volume-overamplified-rtl-symbolic.symbolic.png " Mic volume " " $(wpctl get-volume @DEFAULT_AUDIO_SOURCE@) "
